data_root="./.data_es"

[model]
max_context=512
d_model=128
d_ff=512
h=8
N=6

[tokenizer]
max_sentence_length=16384
input_sentence_size=400000
source_vocab_size=16384
target_vocab_size=16384

[training]
save_every=100
batch_size=32
epochs=10
lr=0.0001

[data]
test_split=0.11