data_root="./.data"

[model]
d_model=512
d_ff=1024
h=8
N=2

[tokenizer]
max_sentence_length=16384
input_sentence_size=400000
source_vocab_size=16384
target_vocab_size=16384

[training]
save_every=1000

[data]
test_split=0.11